### ISSUE TITLE
HTTP Error Response code handling

### ISSUE THREAD

**Issue by garkpit** [brainqub3/meta_expert#18]
While you're in there, coding up great error handling with wonderful logging (please 😆 ) I did see Anthropic returning a 529! Not entirely 'standard' but there you go. Thx 

DEBUG    2024-08-08 13:40:51 - https://api.anthropic.com:443 "POST /v1/messages HTTP/11" 529 75
2024-08-08 13:40:51 - RetryError[<Future at 0x10fa0c190 state=finished raised HTTPError>]
Traceback (most recent call last):
  File "/Users/Jay/anaconda3/envs/meta_expert_env/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/Jay/Dev/AI/john-adeojo(brainqub3)/meta_expert/models/llms.py", line 25, in _make_request
    response.raise_for_status()
  File "/Users/Jay/anaconda3/envs/meta_expert_env/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 529 Server Error:  for url: https://api.anthropic.com/v1/messages

**Comment by garkpit** [comment]
Plenty of 429's from Groq. Perhaps introduce a n millisecond delay between calls.
