### ISSUE TITLE
Error with similarity search

### ISSUE THREAD

**Issue by johntday** [brainqub3/meta_expert#23]
```python
Total documents indexed: 0
Error in indexing and ranking: 'NoneType' object has no attribute 'search'
Traceback (most recent call last):
  File "/Users/johnday/repos/_saas/meta_expert/tools/offline_rag_tool.py", line 150, in index_and_rank
    docs = retriever.similarity_search_with_score(query, k=k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnday/miniconda/envs/agent_env/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 403, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnday/miniconda/envs/agent_env/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 304, in similarity_search_with_score_by_vector
    scores, indices = self.index.search(vector, k if filter is None else fetch_k)
                      ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'search'
```

**Comment by johntday** [comment]
no error
