### ISSUE TITLE
ValueError: Branch did not return a valid destination

### ISSUE THREAD

**Issue by MyraBaba** [brainqub3/meta_expert#4]
INFO     2024-07-27 16:41:41 - Output:
  meta_prompt: [{'role': 'user', 'content': 'None'}, {'role': 'assistant', 'content': 'CoR = {\n    "Goal": "Define the specific purpose that distinguishes the user\'s target companies from general e-commerce sites",\n    "Progress": 0,\n    "User_Preferences": ["Clarity", "Efficiency", "Goal-alignment"],\n    "Adjustments": "Need to clarify the specific purpose to identify specialized criteria for inclusion",\n    "Strategy": [\n        "Step 1: Request clarification on the user\'s purpose to understand the specialized criteria",\n        "Step 2: Identify distinguishing factors that set apart target companies from general e-commerce sites",\n        "Step 3: Define clear and specific criteria for selecting specialized companies"\n    ],\n    "Expertise": "Expertise in defining criteria for company selection, specializing in e-commerce platforms using user-defined purposes",\n    "Verbosity": "med"\n}\n\n<Ex> Expert Planner:\n\n"""\nTask: Request clarification on the user\'s purpose to understand the specialized criteria for selecting companies. Identify distinguishing factors that set apart target companies from general e-commerce sites. Define clear and specific criteria for selecting specialized companies that align with the user\'s purpose.\n"""\n</Ex>'}]
  conversation_history: [HumanMessage(content='CoR = {\n    "Goal": "Understand the user\'s purpose for selecting specialized companies over general e-commerce sites",\n    "Progress": 0,\n    "User_Preferences": ["Clarity", "Efficiency", "Goal-alignment"],\n    "Adjustments": "Need to clarify the specific criteria that differentiate specialized companies from general e-commerce platforms",\n    "Strategy": [\n        "Step 1: Define the user\'s specific purpose for choosing specialized companies",\n        "Step 2: Identify the key characteristics that set specialized companies apart from general e-commerce sites",\n        "Step 3: Establish clear criteria for selecting companies that align with the user\'s purpose"\n    ],\n    "Expertise": "Expertise in understanding user requirements and defining selection criteria for specialized companies over general e-commerce platforms",\n    "Verbosity": "low"\n}\n\n>> FINAL ANSWER:\n\nTo effectively identify specialized companies over general e-commerce sites, it is crucial to define the specific purpose that distinguishes these companies. Once the purpose is clear, key characteristics unique to specialized companies can be identified. These characteristics will serve as the criteria for selecting companies that align with the user\'s purpose, ensuring clarity, efficiency, and goal-alignment in the selection process.', id='ab19652e-940c-4c38-a267-ccdef85e81b1'), AIMessage(content='Your requirements have been successfully captured and processed. If you need any further assistance or modifications, feel free to let me know!', id='8ade9274-78a0-43fd-9778-784bc59e39b7')]
  requirements_gathering: [HumanMessage(content='None', id='ffc13322-5b77-46d3-933f-afc3be1d3797'), AIMessage(content='```python\nCoGoR = {\n    "🎯": "Undefined",\n    "📋": [\n        "Exclude any e-commerce sites not specialized for the user\'s purpose",\n        "Focus on companies"\n    ],\n    "👍🏼": ["Clarity", "Efficiency", "Goal-alignment"],\n    "🔧  ": "Clarify the user\'s purpose to better understand the specialized criteria for inclusion",\n    "🧭": [\n        "1. Define the specific purpose that distinguishes the user\'s target companies from general e-commerce sites",\n        "2. Identify key characteristics that differentiate specialized companies from regular e-commerce platforms",\n        "3. Establish clear criteria for selecting companies that align with the user\'s purpose"\n    ],\n}\n```\n\n👩\u200d💻: Thanks for providing the initial requirements. To further refine them, we need to clarify your primary goal. What specific outcome are you aiming for by focusing on these companies? 🎯\n\n🔍 What are the key characteristics that differentiate specialized companies from regular e-commerce platforms in your context?\n\n🔭 How can we establish clear criteria for selecting companies that align with your purpose while excluding e-commerce sites not specialized for your needs?\n\n🎯 How can we ensure that the selected companies meet your specialized criteria effectively?', id='7d34ffeb-314d-4510-b458-70367a3552af')]
  expert_plan:     role: assistant
    content: Your requirements have been successfully captured and processed. If you need any further assistance or modifications, feel free to let me know!
  expert_research: []
  expert_writing: []
  user_input: [HumanMessage(content='/start', id='f36e44d5-7eff-4202-9175-c9ae011cf37a'), HumanMessage(content='/start', id='e95c1f90-624c-42da-af90-d213a5d9f8cc')]
  previous_search_queries: []
  router_decision: no_tool_expert
  chat_limit: 2
  chat_finished: False
  recursion_limit: 30
DEBUG    2024-07-27 16:41:41 - Execution time: 2.96 seconds
DEBUG    2024-07-27 16:41:41 - Execution time: 2.96 seconds
INFO     2024-07-27 16:41:41 - ========================================

INFO     2024-07-27 16:41:41 - ========================================

DEBUG    2024-07-27 16:41:41 - Starting new HTTPS connection (1): api.openai.com:443
DEBUG    2024-07-27 16:41:41 - Starting new HTTPS connection (1): api.openai.com:443
DEBUG    2024-07-27 16:41:42 - https://api.openai.com:443 "POST /v1/chat/completions HTTP/11" 200 None
DEBUG    2024-07-27 16:41:42 - https://api.openai.com:443 "POST /v1/chat/completions HTTP/11" 200 None

 Routing function called. Decision: None

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bc/Projects/meta_expert/agents/jar3d.py", line 678, in <module>
    for event in workflow.stream(state, limit):
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 963, in stream
    _panic_or_proceed(done, inflight, step)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1489, in _panic_or_proceed
    raise exc
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2408, in invoke
    input = step.invoke(input, config)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/utils.py", line 95, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/graph/graph.py", line 78, in _route
    return self._finish(writer, input, result)
  File "/home/bc/Projects/meta_expert/venvMaeteJag/lib/python3.10/site-packages/langgraph/graph/graph.py", line 109, in _finish
    raise ValueError("Branch did not return a valid destination")
ValueError: Branch did not return a valid destination

**Comment by tonypius** [comment]
I'm getting the same error no matter which combination of config keys I give

**Comment by JarvisChan666** [comment]
same here
